#!/bin/bash

# Initialize variables as empty. Some will have default values, such as directory.
# I wouldn't change too many of these, maybe the directory if you want.
# It'd be cool if we could upload to Google Drive, S3, or something.

DATE=$(date "+%Y%m%d%H%M%S")
DIRECTORY=~/Notes/
SUBJECT=''
TOPIC=''
SYNC=''
BROWSE=''
FIND=''
REPO='https://github.com/luthes/makenotes/'
HELP=$'mn - make notes - Steven Luther
Arguments:
	-s: subject (Required)
	-t: topic (Required)
	-g: git sync
	-d: list notes in directory
	-b: Browse directory
	-f: find in notes titles and contents
	-j: quick jot to $DIR/jots/'

create_notes() {
# Create the notes files and directories.
	if [ -z $SUBJECT ] || [ -z $TOPIC ]
	then
		echo 'Creating notes requires both the -s and -t arguments.'
	else
		mkdir -p ~/Notes/$SUBJECT
		FILE=~/Notes/$SUBJECT/$TOPIC-$DATE.md
		touch $FILE
		echo "# $SUBJECT -- $TOPIC -- $DATE" >> $FILE
		echo "Created file: $FILE" 
	fi
}

list_directory() {
# This should list the Notes directory in the terminal
	for i in $(ls -lsa)
	do 
		echo $i
		ls -lsa $i
	done
}

browse() {
#This open Vim on the default directory top level directory so we can browse, and select which file we want to edit.
	vim $DIRECTORY
}

sync() {
# Sync the files to github.
	if [ ! -d "$DIRECTORY/.git/" ]
	then
		echo 'Initializing directory...'
		git clone $REPO $DIRECTORY
	else
		(cd $DIRECTORY; git pull origin master)
		(cd $DIRECTORY; git push origin master)
	fi
}

find_notes() {
	# Find Matching Titles
	echo 'Matching Files: '
	find -type f -name '*'$FIND'*'
	
	# Find Matching Strings
	echo 'Matching content: '
	grep -rn $FIND $DIRECTORY
}

while getopts ":s:t:gdbfj" opt; do
	case $opt in
		s)
			# Subject
			SUBJECT=$OPTARG
			echo "Subject: $SUBJECT"
			;;
		t)
			#Topic
			TOPIC=$OPTARG
			echo "Topic: $TOPIC"
			create_notes
			;;
		g)
			#Sync
			SYNC=$OPTARG
			sync
			echo "SYNC: $SYNC"
			;;
		d)
			#Directory
			DIRECTORY=$OPTARG
			list_directory		
			echo "DIRECTORY: $DIRECTORY"
			;;
		b)
			#Browse with Vim
			BROWSE=$OPTARG
			browse
			echo "BROWSE: $BROWSE"
			;;
		f)
			#find
			FIND=$OPTARG
			find_notes
			echo "Find: $FIND"
			;;
		*)
			echo "$HELP"
			;;
	esac
done

#shift $((OPTIND-1))
